.TH GENTONES 1
.SH NAME
gentones \- generates tones
.SH SYNOPSIS
gentone wave2alaw <wav file> <alaw file>
.br
gentone wave2ulaw <wav file> <ulaw file>
.br
gentone tone2alaw <frq1> <frq2> <length> <fade in> <fade out> <alaw file>
.br
gentone tone2ulaw <frq1> <frq2> <length> <fade in> <fade out> <ulaw file>
.SH DESCRIPTION
Length and fade lengths must be given in samples (8000 samples are one second).
Tones will append to existing files, wav files don't.
Frequencies may be given as floating point values.
.br
It can be used, to generate law encoded tones with one or two frequencies.
This is mainly used to create patterns, like dial tones, busy tone and other audio
patterns. Depending on your telephone system, you need to use "tones2alaw" or "tones2ulaw".
There are two frequencies to specify "frq1" and "frq2". If only one frequency should be
used, enter 0 for "frq2". The "length" specifies the total length of the tone in samples. 8000
samples are one second. 2000 samples are 1/4 of a second. "fade in" and "fade out" is used to
make the start and stop of the tone soft. If "fade in" is 800, the sound will fade in
within 1/10 of a second.
This makes tones very smooth and avoids the ‘click’ sound at the beginning.
"fade out" respectively. Whatever specified for "fade in" and "fade out", the tone will
be as long as given at "length". If you don’t want to use fades, set "frq1" and "frq2" to
"0". I suggest at least 50 sample for fade to silence. 
.br
The given file will be appended to "alaw file" or "ulaw file". If you like
to create a new one, but the name still exist, delete the file and then start creating it. This
is useful to create a sample with more than one tone. Example: A busy tone normally is made out of
1/2 second of a tone, and one 1/2 second of silence. To add silence, just enter 0 for "frq1"
and "frq2".
.br
It is also possible to convert a wave file to a-law or mu-law. The wave file
must have a sampling rate of 8000. It doesn’t matte what bit-resolution or how many
channels it has (stereo or mono). The sampling rate will not be converted, so it must be
8000 samples/second. The resolution should be 16 bits for best quality. a-law and
mu-law have better resolution than 8 bits. The data of a-law and mu-law is 8 bits
sample, but since it is quantised, the quality will be 12 bits. 12 bits sounds almost as good as 16
bits. Wave files are only available with 8 or 16 bits resolution.
.br
The use of a-law or mu-law files, result in a faster processing, since the
samples must not be converted into a-law or mu-law for ISDN use. ISDN uses only a-law or mu-law
samples.
.SH SEE ALSO
http://www.linux-call-router.de/doc.html
.SH AUTHOR
This minimal man page was written by Victor Seva
<linuxmaniac@torreviejawireless.org>
.br
from documentation created by Andreas Eversberg <jolly@eversberg.eu>
