.TH GENTONES 1
.SH NAME
lcradmin \- view and modify the state of a running lcr
.SH SYNOPSIS
lcradmin state
.br
lcradmin route
.br
lcradmin interface
.br
lcradmin block <port number>
.br
lcradmin unload <port number>
.br
lcradmin unload <port number>
.br
lcradmin release <endpoint id>
.SH DESCRIPTION
.SS lcradmin state
starts lcradmin in interactive mode. You will see
a screen with the current calls and a list of keys for possible
options.
.SS lcradmin route
makes lcr reload the routing.conf
.SS lcradmin interface
makes lcr reload the interface.conf
.SS lcradmin block
makes lcr block the specified port for further
incoming and outgoing calls.
.SS lcradmin unblock
unblocks the port again
.SS lcradmin unload
makes lcr cease using the specified port. The port
the be used by a different application, or to unload the mISDN
driver. To load the port again, use lcradmin unblock as described above,
or use lcradmin interface to reload all interfaces.
.SS lcradmin release
makes lcr release a pending call. The endpoint ID
is shown in the status screen, as well as in the log, starting
with "EP(<ID>)". This can be useful, if two members are joined
in a conference, but they don't or even can't hang up for some
reason. Also lost parked calls can be released.
.SH SEE ALSO
http://www.linux-call-router.de/doc.html
.SH AUTHOR
This minimal man page was written by Joerg Dorchain
<joerg@dorchain.net>
.br
from documentation created by Andreas Eversberg <jolly@eversberg.eu>
